TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJzdWIiOiIxIiwiZXhwIjoxOTAyODczNTk5LCJpYXQiOjE3NzY1Nzk4NzMsImp0aSI6IjYxMDA5ZmZmYzI5YjU2MDZmZmRhNWUzMzc1MTc2NWFiY2JiOGQ2NzA4ZGNkNjU5NjA3YjE4ZjBmN2JiNmYyOTkifQ.K3JhXcLN0K7c4ZfWZ5aej4HX5ozlgs1sEf5cxV70QZIBXkXPIYukBd28_08lOS5xpid0xWW6RCRaBKLyfoez23Yy67v_EFnMz-EhwoNo1eyjDelXjuDfxObkzXRY5JbYO0x1bRC3yTVlhTBqKouq6MXXVXqkRdYIOdZGh6zw-BX7vLHynaczMIsaEmepHZiZ5vKHgvFdWYqFZIIHKqgKx9PCb9GE6JH_2MpuTp-ry3xrGvjolnCa_VktW2V4kuThlv7iWI07nBLp6AVKoMLBrY4Eo-rlBrgs1qauK4sxdIpKBPYN5HbnV8t2xMFZ0bV4kahpcAnD3twu-tkrEgzg4Q"
BASE="https://103.147.52.53:8080"
echo "1. GET /api/me"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -H "Authorization: Bearer $TOKEN" "$BASE/api/me"
echo "2. GET /api/zones"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -H "Authorization: Bearer $TOKEN" "$BASE/api/zones"
echo "3. POST /api/zones"
ZONE_FULL_RESP=$(curl -sk --max-time 10 -w "\nHTTP:%{http_code}" -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name":"test-api-zone","zone_type":"rpz","mode":"slave","master_ip":"1.2.3.4","master_port":53,"sync_interval":3600}' "$BASE/api/zones")
echo "$ZONE_FULL_RESP"
NEW_ZONE_ID=$(echo "$ZONE_FULL_RESP" | head -n 1 | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "4. GET /api/zones/$NEW_ZONE_ID"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -H "Authorization: Bearer $TOKEN" "$BASE/api/zones/$NEW_ZONE_ID"
echo "5. PUT /api/zones/$NEW_ZONE_ID"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X PUT -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name":"test-api-zone","zone_type":"rpz","mode":"slave","master_ip":"9.9.9.9","master_port":53,"sync_interval":7200}' "$BASE/api/zones/$NEW_ZONE_ID"
echo "6. POST /api/zones/$NEW_ZONE_ID/toggle"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X POST -H "Authorization: Bearer $TOKEN" "$BASE/api/zones/$NEW_ZONE_ID/toggle"
echo "7. POST /api/zones/$NEW_ZONE_ID/records"
RECORD_FULL_RESP=$(curl -sk --max-time 10 -w "\nHTTP:%{http_code}" -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name":"malware.example.com","type":"CNAME","value":"rpz-passthru.","ttl":300}' "$BASE/api/zones/$NEW_ZONE_ID/records")
echo "$RECORD_FULL_RESP"
NEW_RECORD_ID=$(echo "$RECORD_FULL_RESP" | head -n 1 | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "8. GET /api/zones/$NEW_ZONE_ID/records"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -H "Authorization: Bearer $TOKEN" "$BASE/api/zones/$NEW_ZONE_ID/records"
echo "9. DELETE /api/zones/$NEW_ZONE_ID/records/$NEW_RECORD_ID"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X DELETE -H "Authorization: Bearer $TOKEN" "$BASE/api/zones/$NEW_ZONE_ID/records/$NEW_RECORD_ID"
echo "10. GET /api/ipfilters"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -H "Authorization: Bearer $TOKEN" "$BASE/api/ipfilters"
echo "11. POST /api/ipfilters"
FILTER_FULL_RESP=$(curl -sk --max-time 10 -w "\nHTTP:%{http_code}" -X POST -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"cidr":"192.168.99.0/24","description":"test-api-filter"}' "$BASE/api/ipfilters")
echo "$FILTER_FULL_RESP"
NEW_FILTER_ID=$(echo "$FILTER_FULL_RESP" | head -n 1 | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "12. POST /api/ipfilters/$NEW_FILTER_ID/toggle"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X POST -H "Authorization: Bearer $TOKEN" "$BASE/api/ipfilters/$NEW_FILTER_ID/toggle"
echo "13. DELETE /api/ipfilters/$NEW_FILTER_ID"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X DELETE -H "Authorization: Bearer $TOKEN" "$BASE/api/ipfilters/$NEW_FILTER_ID"
echo "14. DELETE /api/zones/$NEW_ZONE_ID"
curl -sk --max-time 10 -w "\nHTTP:%{http_code}\n" -X DELETE -H "Authorization: Bearer $TOKEN" "$BASE/api/zones/$NEW_ZONE_ID"
